#!/bin/bash
set -e
tweegoFolder="./tweego"

mkdir -p "$tweegoFolder"
tempFile="$tweegoFolder/tweegoTemp"

wget "https://www.motoslave.net/tweego/download.php/tweego-$1-linux-x64.zip" -O "$tempFile"
unzip -o -j "$tempFile" "tweego" -d "$tweegoFolder"

rm $tempFile
chmod a+x "$tweegoFolder/tweego"
