#!/bin/bash
story_formats_dir="./story-formats"
mkdir -p "$story_formats_dir"

poof_path="./$story_formats_dir/poof/format.js"

if [ -f "$poof_path" ]; then
  rm -f "$poof_path"
fi

wget "https://cdn.jsdelivr.net/gh/chapelr/poof@latest/docs/use/format.js" -P "./$story_formats_dir/poof"
