#!/bin/bash
set -e

# Remove trailing slash from path if there's one
path=${1%/}

echo "Path $1 $path"

if [[ -z "$path" ]]; then
    echo "First argument must not be blank, it must be the path to a story folder"
    exit 1
fi

if [ ! -d "$path" ]; then
    echo "First argument must be the path to a story folder"
    exit 1
fi

if [ ! -f "./$path/styles/styles.scss" ]; then
    echo "First argument must be a path to a story folder that contains a /styles/styles.scss file"
    exit 1
fi

if [ ! -f "./$path/scripts/index.js" ]; then
    echo "First argument must be a path to a story folder that contains a /scripts/index.js file"
    exit 1
fi

if [ ! -d "./$path/twee" ]; then
    echo "First argument must be a path to a story folder that contains a /twee folder"
    exit 1
fi

npm config set chapbook-tweego-starter:storyPath "$path"
